### ISSUE TITLE
Keyboard PopUp on mobile devices

### ISSUE THREAD

**Issue by crokitta** [Dani3lSun/apex-plugin-clockpicker#3]
Hi Daniel,

I was experimenting with this jQuery plugIn as well. The one problem I have with it, and you haven't been able to solve this too, is, that on mobile devices (tested it on Android) the default keyboard is poping up when you focus on the input field. Any idea, how to prevent this behaviour?

Regards,
Christian Rokitta

**Comment by Dani3lSun** [comment]
Hi Christian,
I think I solved it with a simple onfocus="blur();" on the input field. I changed it on my demo app (https://apex.oracle.com/pls/apex/f?p=57743:3). I tested it on iOS and the keyboard is not fading up, can you please test it with Android? Thanks for your hint, tested it by now only on desktop browsers...

- Daniel
