### ISSUE TITLE
APEX 4.2 Not able to import plugin

### ISSUE THREAD

**Issue by molashaw** [Dani3lSun/apex-plugin-clockpicker#4]
'File is not a valid Application Express plug-in export file.' when i try to import the .sql file into 4.2. Is this plugin only for 5.0?

**Comment by Dani3lSun** [comment]
The plugin is developed on APEX 5, thus the export file is not compatible with earlier releases of APEX. I looked a bit into the generated Export SQL file, and there are many differences from 4.2 to 5. Maybe I can produce a plugin for version 4.2, but for that I have to find a running env first of all...All my instances are upgraded to APEX 5...

**Comment by molashaw** [comment]
Thanks for the quick response. We will be upgrading to 5.0 later this year
so i will use your very awesome clock plugin then :-).

On Thu, Oct 29, 2015 at 5:14 PM, Daniel Hochleitner <
notifications@github.com> wrote:

> The plugin is developed on APEX 5, thus the export file is not compatible
> with earlier releases of APEX. I looked a bit into the generated Export SQL
> file, and there are many differences from 4.2 to 5. Maybe I can produce a
> plugin for version 4.2, but for that I have to find a running env first of
> all...All my instances are upgraded to APEX 5...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dani3lSun/apex-plugin-clockpicker/issues/4#issuecomment-152329932>
> .
>



-- 
Morgan A. Lashaw
