### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by maxhorizon** [Dani3lSun/apex-plugin-clockpicker#6]
Hi,

For some reasons I am getting the following error:

Failed to load resource: the server responded with a status of 404 (Not Found)

for the following resources:

http://localhost:6080/ords/dev/r/129/files/plugin/11194280148882394590/v23/css/bootstrap-clockpicker.min.css

http://localhost:6080/ords/dev/r/129/files/plugin/11194280148882394590/v23/js/bootstrap-clockpicker.min.js

http://localhost:6080/ords/dev/r/129/files/plugin/11194280148882394590/v23/css/bootstrap.min.css

It works fine if I upload the files to my file server and change the plugin prefix.

Regards,
Salim

**Comment by Dani3lSun** [comment]
I see you use ORDS, maybe you have forgotten something in your installation:
https://community.oracle.com/thread/3774608?start=0&tstart=0
I had a similar issue a couple of months ago and
```
alter user WORKSPACE_USER grant connect through APEX_REST_PUBLIC_USER;
```
solved it for me...

**Comment by Dani3lSun** [comment]
I close this issue now.
If you still have problems, just write here again!
