### ISSUE TITLE
File is not a valid plug-in in APEX 5

### ISSUE THREAD

**Issue by JonaxelN** [Dani3lSun/apex-plugin-clockpicker#7]
When I try to install plugin into my application I get the next error:

**File is not a valid Application Express plug-in export file.**

I'm working on apex 5

**Comment by Dani3lSun** [comment]
Hi @JonaxelN 
I can´t reproduce your issue in any of my instances...Tested the import on two APEX 5.0.3 and one APEX 5.0.2 instances, all worked fine...On which exact version are you? Have you imported the correct sql file from source directory "item_type_plugin_de_danielh_clockpicker.sql" ?

**Comment by JonaxelN** [comment]
Hi apparently I resolved this issue, I downloaded the same plugin from apex.world and it worked. The plugin from github doesn't work for me.I'm ussing APEX 5.0.2

**Comment by Dani3lSun** [comment]
Ok that´s a bit strange, because apex.world does nothing more than using a link to github for the most recent plugin version...^^ So it doesn´t matter which one you use, both come from github...
But if it works, it´s great!:)

**Comment by JonaxelN** [comment]
Yes, I was downloading the file with right click and save file as... but you have to left click and copy all the text and save it in notepad or something like that with the extension sql. Thank you for your considerations

**Comment by Dani3lSun** [comment]
Ah ok, you downloaded the file from github source browser...please download always from the "releases" tab! The other files are the most recent source code, which means it can be buggy...
